"""empty message

Revision ID: a57277f0338c
Revises: 
Create Date: 2022-10-12 23:36:24.286335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57277f0338c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_email'), 'guest', ['email'], unique=True)
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=True)
    op.create_index(op.f('ix_guest_phone'), 'guest', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_phone'), table_name='guest')
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_index(op.f('ix_guest_email'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
